// 自動生成ファイル。編集しないでください。

export type GallerySet = {
  slug: string;
  title: string;
  cover: string;
  images: string[];
  isR18: boolean;
};

export type Gallery = {
  slug: string;
  category: string;
  title: string;
  sets: GallerySet[];
};

export const galleries: Gallery[] = [
  {
    "slug": "tolove-ru-lala",
    "category": "ToLOVE-ru",
    "title": "ララ・サタリン・デビルーク",
    "sets": [
      {
        "slug": "cheerleader",
        "title": "チアリーダー",
        "cover": "/images/gallery/ToLOVE-ru/lala/cheerleader/cover.webp",
        "images": [
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00001.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00002.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00003.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00004.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00005.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00006.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00008.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00009.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00010.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00011.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00013.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00014.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00015.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00016.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00017.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00018.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00019.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00020.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00021.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00022.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00023.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00024.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00025.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00026.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00027.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00028.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00029.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00030.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00031.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00032.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00033.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00034.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00035.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00036.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00037.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00038.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00039.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00040.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00041.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00042.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00043.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00044.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00045.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00046.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00047.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00048.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00049.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00050.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00051.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00052.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00053.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00054.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00055.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00056.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00057.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00058.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00059.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00060.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00061.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00062.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00063.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00064.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00065.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00066.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00067.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00068.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00069.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00070.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00071.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00072.webp",
          "/images/gallery/ToLOVE-ru/lala/cheerleader/00213.webp"
        ],
        "isR18": false
      },
      {
        "slug": "r18_shower",
        "title": "シャワー",
        "cover": "/images/gallery/ToLOVE-ru/lala/r18_shower/cover.webp",
        "images": [
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_20908_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_20909_ copy.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_20931_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_20934_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_20940_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_20941_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_20953_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_20961_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21005_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21007_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21008_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21029_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21033_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21035_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21036_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21045_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21058_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21066_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21069_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21070_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21077_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21102_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21103_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21108_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21109_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21313_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21314_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21315_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21328_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21329_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21339_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21340_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21347_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21348_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21350_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21351_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21362_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21368_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21372_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21375_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21377_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21379_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21380_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21381_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21382_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21383_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21394_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21395_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21429_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21441_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21443_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21444_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21453_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21454_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21456_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21457_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21468_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21469_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21471_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21472_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21473_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21476_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21479_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21480_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21481_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21483_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21496_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21497_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21501_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21502_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21535_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21536_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21550_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21567_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21568_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21579_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21590_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21591_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21604_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21606_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21643_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21644_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21653_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21671_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21672_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21676_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21680_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21681_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21682_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21687_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21706_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21707_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21710_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21711_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21712_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21713_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21720_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21722_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21732_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21733_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21751_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21757_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21763_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21765_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21784_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21795_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21796_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21808_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21809_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21811_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21832_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21843_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21844_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21852_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21858_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21859_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21877_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21878_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21887_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21889_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21893_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21914_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21918_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21944_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21947_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21949_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21951_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21957_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21958_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21965_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21966_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21970_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21980_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21990_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21991_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21997_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_21999_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22000_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22002_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22012_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22013_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22024_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22025_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22038_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22048_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22049_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22050_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22061_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22068_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22070_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22081_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22082_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22083_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22091_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22092_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22094_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22103_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22104_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22107_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22122_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22123_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22136_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22137_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22148_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22149_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22160_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22179_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22180_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22182_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22189_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22200_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22202_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22216_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22222_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22223_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22224_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22241_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22279_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22282_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22291_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22292_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22303_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22309_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22310_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22312_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22314_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22324_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22327_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22334_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22367_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22368_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22369_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22386_.webp",
          "/images/gallery/ToLOVE-ru/lala/r18_shower/ComfyUI_22389_.webp"
        ],
        "isR18": true
      }
    ]
  },
  {
    "slug": "tolove-ru-yami",
    "category": "ToLOVE-ru",
    "title": "金色の闇",
    "sets": [
      {
        "slug": "forest",
        "title": "forest",
        "cover": "/images/gallery/ToLOVE-ru/yami/forest/cover.webp",
        "images": [
          "/images/gallery/ToLOVE-ru/yami/forest/ComfyUI_16721_.webp",
          "/images/gallery/ToLOVE-ru/yami/forest/ComfyUI_16723_.webp",
          "/images/gallery/ToLOVE-ru/yami/forest/ComfyUI_16726_.webp",
          "/images/gallery/ToLOVE-ru/yami/forest/ComfyUI_16731_.webp"
        ],
        "isR18": false
      }
    ]
  },
  {
    "slug": "tolove-ru-momo",
    "category": "ToLOVE-ru",
    "title": "モモ・ベリア・デビルーク",
    "sets": [
      {
        "slug": "pajamas",
        "title": "pajamas",
        "cover": "/images/gallery/ToLOVE-ru/momo/pajamas/cover.webp",
        "images": [
          "/images/gallery/ToLOVE-ru/momo/pajamas/ComfyUI_23908_.webp",
          "/images/gallery/ToLOVE-ru/momo/pajamas/ComfyUI_23913_.webp",
          "/images/gallery/ToLOVE-ru/momo/pajamas/ComfyUI_23926_.webp",
          "/images/gallery/ToLOVE-ru/momo/pajamas/ComfyUI_23955_.webp"
        ],
        "isR18": false
      }
    ]
  },
  {
    "slug": "tolove-ru-mea",
    "category": "ToLOVE-ru",
    "title": "黒咲芽亜",
    "sets": [
      {
        "slug": "beach",
        "title": "beach",
        "cover": "/images/gallery/ToLOVE-ru/mea/beach/cover.webp",
        "images": [
          "/images/gallery/ToLOVE-ru/mea/beach/ComfyUI_09348_.webp",
          "/images/gallery/ToLOVE-ru/mea/beach/ComfyUI_09379_.webp",
          "/images/gallery/ToLOVE-ru/mea/beach/ComfyUI_09389_.webp",
          "/images/gallery/ToLOVE-ru/mea/beach/ComfyUI_09390_.webp"
        ],
        "isR18": false
      }
    ]
  },
  {
    "slug": "tolove-ru-mikan",
    "category": "ToLOVE-ru",
    "title": "結城美柑",
    "sets": [
      {
        "slug": "date",
        "title": "date",
        "cover": "/images/gallery/ToLOVE-ru/mikan/date/cover.webp",
        "images": [
          "/images/gallery/ToLOVE-ru/mikan/date/ComfyUI_01291_.webp",
          "/images/gallery/ToLOVE-ru/mikan/date/ComfyUI_01319_.webp",
          "/images/gallery/ToLOVE-ru/mikan/date/ComfyUI_01342_.webp",
          "/images/gallery/ToLOVE-ru/mikan/date/ComfyUI_01382_.webp"
        ],
        "isR18": false
      }
    ]
  },
  {
    "slug": "original-game-charactor",
    "category": "original",
    "title": "ゲームキャラクター",
    "sets": [
      {
        "slug": "normal",
        "title": "通常衣装",
        "cover": "/images/gallery/original/game-charactor/normal/cover.webp",
        "images": [
          "/images/gallery/original/game-charactor/normal/ComfyUI_06861_.webp",
          "/images/gallery/original/game-charactor/normal/ComfyUI_06934_.webp",
          "/images/gallery/original/game-charactor/normal/ComfyUI_07315_.webp",
          "/images/gallery/original/game-charactor/normal/ComfyUI_07350_.webp"
        ],
        "isR18": false
      }
    ]
  }
];
